### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [eseer-divad/Qiskit-Programs#1]
I recently came across your project Qiskit-Programs and I noticed that the repository github.com/eseer-divad/Qiskit-Programs currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by eseer-divad** [comment]
Hello Dr. Cruz-Benito,

I have added the Apache 2.0 License.

Thank you for taking the time to look at my repo and open an issue! I had no idea neglecting to select a license causes problems, but I can see why now. I will revisit this repository and attempt to get more of this program working in December, it is just a starting point for me at the moment.

I'll be taking a course in Quantum Physics in the Spring, and this will be a lengthy notebook that may serve to introduce my peers at college to Qiskit. By then I'd like to have some programs working that I can show off running on your guys' hardware in the cloud.

-- Good luck in your projects! -- David Reese

**Comment by cbjuan** [comment]
Thanks
